### ISSUE TITLE
What about other stuff

### ISSUE THREAD

**Issue by darthnithin** [shrey150/protobowl-bot#1]
So this doesnt work with hs?

**Comment by shrey150** [comment]
No, I haven't set it up to work with HS (mostly bc its more fun with MS kids), but another issue is that not all question sets from high school may be on my source, the QuizDB API. I can look into this, and maybe add an autodetection feature for the bot to differentiate between MS/HS rooms.

**Comment by darthnithin** [comment]
I tried to change that by changing the search in query to Quiz DB Api and ran it, It worked for the first question and then stopped. It is because of the different difficulties, (and therefore categories) in HS quiz bowl and quizdb

Thanks,
Nithin

**Comment by shrey150** [comment]
Yeah, that's what I was saying, I did some manual testing some while back and not all of hsquizbowl's questions are on QuizDB. The only way this would be possible was if someone wrote a "scraper" of sorts for the bot that just saves questions and answer lines to a new DB that the bot would use.

**Comment by darthnithin** [comment]
cwl

**Comment by darthnithin** [comment]
how would you do that?

**Comment by darthnithin** [comment]
Maybe we could scrape from protobowl's ridiculously long question list.

**Comment by Nithindanday** [comment]
Update: MS public rooms are now broken. Maybe we should implement a way to disable the bots from chat
