### ISSUE TITLE
QuizDB API wrapper offline

### ISSUE THREAD

**Issue by shrey150** [shrey150/protobowl-bot#4]
having some problems with my personal server that's hosting my PHP wrapper for the bot, it's currently not function right now

**Comment by darthnithin** [comment]
What does the PHP wrapper do? Your comment says it bypasses Cross origin blocking. But couldn't you use it without the server by turning off the same origin policy on chrome?

**Comment by shrey150** [comment]
I'm pretty sure it's a built in feature; to disable it, that has to be done from the server itself, which means i obviously wouldn't have access to Protobowls settings. That's why I wrote the wrapper.

Also, I've been lazy and haven't set up my server since it just crashed, I'll get it back up at some point

**Comment by shrey150** [comment]
fixed, using a NodeJS wrapper now. the bot is now functional again
